name: Build & Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write      # to create the GitHub Release
  packages: read

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      APP_NAME: Crunchy
      ARTIFACT_ROOT: publish

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Get project version
        id: get-version
        uses: kzrnm/get-net-sdk-project-versions-action@v2
        with:
          proj-path: '${{ env.APP_NAME }}/${{ env.APP_NAME }}.csproj'

      - name: Publish Executable & Dependencies
        run: |
          # make sure the folder exists
          mkdir -p ${{ env.ARTIFACT_ROOT }}/${{ env.APP_NAME }}
          # publish into that folder
          dotnet publish ${{ env.APP_NAME }}/${{ env.APP_NAME }}.csproj \
            --configuration Release \
            --output ${{ env.ARTIFACT_ROOT }}/${{ env.APP_NAME }}

      - name: Copy data files
        run: |
          # copy ONLY the contents of Data/ into publish/Crunchy/
          cp -R ./Data/. ${{ env.ARTIFACT_ROOT }}/${{ env.APP_NAME }}/

      - name: Zip artifacts
        id: zip
        run: |
          VERSION=${{ steps.get-version.outputs.version }}
          ZIP="${{ env.APP_NAME }}-${VERSION}.zip"
          # move into the root of our artifacts
          cd ${{ env.ARTIFACT_ROOT }}
          # zip the entire Crunchy/ folder
          zip -r "../${ZIP}" "${{ env.APP_NAME }}"
          # expose the ZIP name for the next step
          echo "ZIP=${ZIP}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get-version.outputs.version }}
          name: Release ${{ steps.get-version.outputs.version }}
          files: ${{ steps.zip.outputs.ZIP }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
